// Aluno: lucas Martins da Silva Sena - RA: a2348098 - ok

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Lucas_Sena
 */
public class CadAtendente extends javax.swing.JFrame {

    private Atendente atendente;
    private GerEntidades gerEntidades = new GerEntidades();
    
    private static CadAtendente unicoCadAtendente;

    /**
     * Creates new form CadAtendente
     */
    private CadAtendente() {
        initComponents();
    }
    
    public static CadAtendente getCadAtendente() {
        if (unicoCadAtendente == null) {
            unicoCadAtendente = new CadAtendente();
        }
        return unicoCadAtendente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgencia = new javax.swing.JLabel();
        lblEndereco1 = new javax.swing.JLabel();
        ctBanco = new javax.swing.JTextField();
        lblBanco = new javax.swing.JLabel();
        lblDigito = new javax.swing.JLabel();
        lblNumeroCartao = new javax.swing.JLabel();
        ctDigito = new javax.swing.JTextField();
        ctNumeroCartao = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        lblFilme = new javax.swing.JLabel();
        lblDadosPessoais = new javax.swing.JLabel();
        ctNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        ctEmail = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        ctCpf = new javax.swing.JTextField();
        lblIdade = new javax.swing.JLabel();
        ctIdade = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        ctTelefone = new javax.swing.JTextField();
        lblSobrenome = new javax.swing.JLabel();
        ctSobrenome = new javax.swing.JTextField();
        ctRua = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        ctCep = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        ctBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        ctCidade = new javax.swing.JTextField();
        ctNumero = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        ctEstado = new javax.swing.JTextField();
        lblRua = new javax.swing.JLabel();
        ctOperacao = new javax.swing.JTextField();
        lblOperacao = new javax.swing.JLabel();
        ctAgencia = new javax.swing.JTextField();
        lblCargo = new javax.swing.JLabel();
        ctCargo = new javax.swing.JTextField();
        lblSalario = new javax.swing.JLabel();
        ctSalario = new javax.swing.JTextField();
        lblCarteiraTrabalho = new javax.swing.JLabel();
        ctCarteiraTrabalho = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAtendente = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAgencia.setBackground(new java.awt.Color(0, 0, 0));
        lblAgencia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblAgencia.setText("Agência:");

        lblEndereco1.setBackground(new java.awt.Color(0, 0, 0));
        lblEndereco1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEndereco1.setText("CONTA BANCÁRIA");

        lblBanco.setBackground(new java.awt.Color(0, 0, 0));
        lblBanco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblBanco.setText("Banco:");

        lblDigito.setBackground(new java.awt.Color(0, 0, 0));
        lblDigito.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblDigito.setText("Digito:");

        lblNumeroCartao.setBackground(new java.awt.Color(0, 0, 0));
        lblNumeroCartao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNumeroCartao.setText("Número do Cartão: ");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        lblFilme.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblFilme.setText("ATENDENTE");

        lblDadosPessoais.setBackground(new java.awt.Color(0, 0, 0));
        lblDadosPessoais.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblDadosPessoais.setText("DADOS PESSOAIS");

        lblNome.setBackground(new java.awt.Color(0, 0, 0));
        lblNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        lblEmail.setBackground(new java.awt.Color(0, 0, 0));
        lblEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEmail.setText("Email:");

        lblCpf.setBackground(new java.awt.Color(0, 0, 0));
        lblCpf.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCpf.setText("Cpf:");

        lblIdade.setBackground(new java.awt.Color(0, 0, 0));
        lblIdade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblIdade.setText("Idade:");

        lblTelefone.setBackground(new java.awt.Color(0, 0, 0));
        lblTelefone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTelefone.setText("Telefone:");

        lblSobrenome.setBackground(new java.awt.Color(0, 0, 0));
        lblSobrenome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblSobrenome.setText("Sobrenome:");

        lblCep.setBackground(new java.awt.Color(0, 0, 0));
        lblCep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCep.setText("CEP:");

        lblBairro.setBackground(new java.awt.Color(0, 0, 0));
        lblBairro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblBairro.setText("Bairro:");

        lblCidade.setBackground(new java.awt.Color(0, 0, 0));
        lblCidade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCidade.setText("Cidade:");

        lblNumero.setBackground(new java.awt.Color(0, 0, 0));
        lblNumero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNumero.setText("Numero:");

        lblEndereco.setBackground(new java.awt.Color(0, 0, 0));
        lblEndereco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEndereco.setText("ENDERECO");

        lblEstado.setBackground(new java.awt.Color(0, 0, 0));
        lblEstado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEstado.setText("Estado:");

        lblRua.setBackground(new java.awt.Color(0, 0, 0));
        lblRua.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblRua.setText("rua:");

        lblOperacao.setBackground(new java.awt.Color(0, 0, 0));
        lblOperacao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblOperacao.setText("Operação:");

        lblCargo.setBackground(new java.awt.Color(0, 0, 0));
        lblCargo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCargo.setText("Cargo:");

        lblSalario.setBackground(new java.awt.Color(0, 0, 0));
        lblSalario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblSalario.setText("Salario:");

        lblCarteiraTrabalho.setBackground(new java.awt.Color(0, 0, 0));
        lblCarteiraTrabalho.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCarteiraTrabalho.setText("N° da Carteira de Trabalho:");

        btCadastrar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btCadastrar.setText("CADASTRAR");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar Dados ");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar Dados");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        tblAtendente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Email", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(tblAtendente);

        btExcluir.setText("Excluir Conta");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCargo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSalario))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblNome)
                                                .addGap(29, 29, 29)
                                                .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblEmail)
                                            .addComponent(lblCpf))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTelefone, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblSobrenome, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblIdade, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ctSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ctTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                        .addComponent(ctIdade, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                        .addComponent(ctSobrenome))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBanco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ctBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDigito)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ctDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOperacao, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAgencia, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(ctOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ctAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblBairro)
                                            .addComponent(lblRua))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ctRua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ctBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ctCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ctEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ctCep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ctNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumeroCartao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctNumeroCartao))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(335, 335, 335)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblCep, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(309, 309, 309)
                                        .addComponent(lblEndereco))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(288, 288, 288)
                                        .addComponent(lblEndereco1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCarteiraTrabalho)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ctCarteiraTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ctCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ctEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ctCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFilme)
                                    .addComponent(lblDadosPessoais))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btExcluir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btConsultar)
                                    .addGap(198, 198, 198)
                                    .addComponent(btAlterar))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblFilme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDadosPessoais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(ctEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCpf)
                            .addComponent(ctCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSobrenome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdade))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCargo)
                        .addComponent(ctCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ctSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSalario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarteiraTrabalho)
                    .addComponent(ctCarteiraTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(lblEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCidade)
                            .addComponent(ctCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBairro)
                            .addComponent(ctBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCep))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumero))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEndereco1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBanco)
                            .addComponent(ctBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDigito)
                            .addComponent(ctDigito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumeroCartao)
                            .addComponent(ctNumeroCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAgencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOperacao))))
                .addGap(18, 18, 18)
                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultar)
                    .addComponent(btAlterar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadastrarAtendente();
        listarTabela();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultarAtendente();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterarAtendente();
        listarTabela();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluirAtendente();
        listarTabela();
    }//GEN-LAST:event_btExcluirActionPerformed

    public void cadastrarAtendente() {
        Atendente atendente = new Atendente();

        //try null pointer exception
        try {
            try {

                atendente.setEmail(ctEmail.getText());
                try {
                    atendente.setTelefone(ctTelefone.getText());
                    try {
                        atendente.setIdade(Integer.parseInt(ctIdade.getText()));
                        atendente.setNome(ctNome.getText());
                        atendente.setSobrenome(ctSobrenome.getText());
                        atendente.setCpf(ctCpf.getText());
                        atendente.setCargo(ctCargo.getText());
                        atendente.setSalario(Integer.parseInt(ctSalario.getText()));
                        atendente.setNCarteiraTrabalho(ctCarteiraTrabalho.getText());

                        atendente.getEndereco().setCidade(ctCidade.getText());
                        atendente.getEndereco().setEstado(ctEstado.getText());
                        atendente.getEndereco().setRua(ctRua.getText());
                        atendente.getEndereco().setCep(ctCep.getText());
                        atendente.getEndereco().setBairro(ctBairro.getText());
                        atendente.getEndereco().setNumero(ctNumero.getText());

                        atendente.getConta().setBanco(ctBanco.getText());
                        atendente.getConta().setAgencia(ctAgencia.getText());
                        atendente.getConta().setDigito(ctDigito.getText());
                        atendente.getConta().setOperacao(ctOperacao.getText());
                        atendente.getConta().setNumeroCartao(ctNumeroCartao.getText());

                        atendente = gerEntidades.cadastraAtendente(atendente);
                        if (atendente != null) {
                            JOptionPane.showMessageDialog(null, "Atendente cadastrado com sucesso!", "Cadastro de Atendente", JOptionPane.INFORMATION_MESSAGE);
                            limpar();
                        } else {
                            JOptionPane.showMessageDialog(null, "Atendente não cadastrado!", "Cadastro de Atendente", JOptionPane.ERROR_MESSAGE);
                            limpar();
                        }
                    } catch (NumberFormatException nfe) {
                        JOptionPane.showMessageDialog(null, "Idade deve ser um inteiro", "Erro no tipo de dado", JOptionPane.ERROR_MESSAGE);
                        ctIdade.setText("");
                        ctIdade.requestFocus();
                    }
                } catch (TelefoneFormatException nfe) {
                    nfe.impTelefoneFormat();
                    ctTelefone.setText("");
                    ctTelefone.requestFocus();
                }

            } catch (EmailFormatException efe) {
                efe.impEmailFormat();
                ctEmail.setText("");
                ctEmail.requestFocus();
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "EMAIL deve ser um String");
                ctEmail.setText("");
                ctEmail.requestFocus();
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Erro de Preenchimento", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void consultarAtendente() {
        atendente = new Atendente();
        atendente.setCpf(ctCpf.getText());
        atendente = gerEntidades.consultaAtendente(atendente);

        if (atendente != null) {
            ctNome.setText(atendente.getNome());
            ctSobrenome.setText(atendente.getSobrenome());
            ctEmail.setText(atendente.getEmail());
            ctTelefone.setText(atendente.getTelefone());
            ctCpf.setText(atendente.getCpf());
            ctIdade.setText(String.valueOf(atendente.getIdade()));
            ctCargo.setText(atendente.getCargo());
            ctCarteiraTrabalho.setText(atendente.getNCarteiraTrabalho());
            ctSalario.setText(Float.toString(atendente.getSalario()));

            ctCidade.setText(atendente.getEndereco().getCidade());
            ctEstado.setText(atendente.getEndereco().getEstado());
            ctRua.setText(atendente.getEndereco().getRua());
            ctCep.setText(atendente.getEndereco().getCep());
            ctBairro.setText(atendente.getEndereco().getBairro());
            ctNumero.setText(atendente.getEndereco().getNumero());

            ctBanco.setText(atendente.getConta().getBanco());
            ctAgencia.setText(atendente.getConta().getAgencia());
            ctDigito.setText(atendente.getConta().getDigito());
            ctOperacao.setText(atendente.getConta().getOperacao());
            ctNumeroCartao.setText(atendente.getConta().getNumeroCartao());
        } else {
            JOptionPane.showMessageDialog(null, "Atendente não encontrado!", "Consulta de Atendente", JOptionPane.ERROR_MESSAGE);
            limpar();
        }
    }

    public void alterarAtendente() {
        atendente = new Atendente();
        atendente.setCpf(ctCpf.getText());
        atendente = gerEntidades.alterarAtendente(atendente);

        if (atendente != null) {
            ctNome.setText(atendente.getNome());
            ctSobrenome.setText(atendente.getSobrenome());
            //ctEmail.setText(atendente.getEmail());
            //ctTelefone.setText(atendente.getTelefone());
            ctIdade.setText(String.valueOf(atendente.getIdade()));
            ctCargo.setText(atendente.getCargo());
            ctCarteiraTrabalho.setText(atendente.getNCarteiraTrabalho());
            ctSalario.setText(Float.toString(atendente.getSalario()));

            ctCidade.setText(atendente.getEndereco().getCidade());
            ctEstado.setText(atendente.getEndereco().getEstado());
            ctRua.setText(atendente.getEndereco().getRua());
            ctCep.setText(atendente.getEndereco().getCep());
            ctBairro.setText(atendente.getEndereco().getBairro());
            ctNumero.setText(atendente.getEndereco().getNumero());

            ctBanco.setText(atendente.getConta().getBanco());
            ctAgencia.setText(atendente.getConta().getAgencia());
            ctDigito.setText(atendente.getConta().getDigito());
            ctOperacao.setText(atendente.getConta().getOperacao());
            ctNumeroCartao.setText(atendente.getConta().getNumeroCartao());

            JOptionPane.showMessageDialog(null, "Atendente encontrado!", "Alterar Atendente", JOptionPane.INFORMATION_MESSAGE);
            limpar();
        } else {
            JOptionPane.showMessageDialog(null, "Atendente não encontrado!", "Alterar Atendente", JOptionPane.ERROR_MESSAGE);
            limpar();
        }
    }

    public void excluirAtendente() {
        atendente = new Atendente();
        atendente.setCpf(ctCpf.getText());
        atendente = gerEntidades.consultaAtendente(atendente);

        if (atendente != null) {
            ctNome.setText(atendente.getNome());
            ctSobrenome.setText(atendente.getSobrenome());
            ctEmail.setText(atendente.getEmail());
            ctTelefone.setText(atendente.getTelefone());
            ctCpf.setText(atendente.getCpf());
            ctIdade.setText(String.valueOf(atendente.getIdade()));
            ctCargo.setText(atendente.getCargo());
            ctCarteiraTrabalho.setText(atendente.getNCarteiraTrabalho());
            ctSalario.setText(Float.toString(atendente.getSalario()));

            ctCidade.setText(atendente.getEndereco().getCidade());
            ctEstado.setText(atendente.getEndereco().getEstado());
            ctRua.setText(atendente.getEndereco().getRua());
            ctCep.setText(atendente.getEndereco().getCep());
            ctBairro.setText(atendente.getEndereco().getBairro());
            ctNumero.setText(atendente.getEndereco().getNumero());

            ctBanco.setText(atendente.getConta().getBanco());
            ctAgencia.setText(atendente.getConta().getAgencia());
            ctDigito.setText(atendente.getConta().getDigito());
            ctOperacao.setText(atendente.getConta().getOperacao());
            ctNumeroCartao.setText(atendente.getConta().getNumeroCartao());

            int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente remover o Atendente?", "Remover Atendente", JOptionPane.YES_NO_OPTION);
            if (opcao == JOptionPane.YES_OPTION) {
                atendente = gerEntidades.removeAtendente(atendente);
                if (atendente != null) {
                    JOptionPane.showMessageDialog(null, "Atendente removido com sucesso!", "Remover Atendente", JOptionPane.INFORMATION_MESSAGE);
                    limpar();
                } else {
                    JOptionPane.showMessageDialog(null, "Atendente não removido!", "Remover Atendente", JOptionPane.ERROR_MESSAGE);
                    limpar();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Atendente não encontrado!", "Remover Atendente", JOptionPane.ERROR_MESSAGE);
            limpar();
        }
    }

    public void listarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tblAtendente.getModel();
        int posLinha = 0; // indice para percorrer a tabela

        modelo.setRowCount(posLinha); // indica a primeira linha da tabela

        for (Atendente atendente : gerEntidades.getBdAtendente()) {
            modelo.insertRow(posLinha, new Object[]{atendente.getNome(), atendente.getEmail(), atendente.getTelefone()});
            posLinha++;
        }
    }

    public void sair() {
        // yes = 0
        int resp = JOptionPane.showConfirmDialog(null, "Deseja Sair?", "Saída", JOptionPane.YES_NO_CANCEL_OPTION);

        if (resp == 0) {
            this.dispose();
        }
    }

    public void limpar() {
        ctNome.setText("");
        ctSobrenome.setText("");
        ctEmail.setText("");
        ctTelefone.setText("");
        ctCpf.setText("");
        ctIdade.setText("");
        ctCarteiraTrabalho.setText("");
        ctCargo.setText("");
        ctSalario.setText("");
        ctCidade.setText("");
        ctEstado.setText("");
        ctRua.setText("");
        ctCep.setText("");
        ctBairro.setText("");
        ctNumero.setText("");
        ctBanco.setText("");
        ctAgencia.setText("");
        ctDigito.setText("");
        ctOperacao.setText("");
        ctNumeroCartao.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadAtendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField ctAgencia;
    private javax.swing.JTextField ctBairro;
    private javax.swing.JTextField ctBanco;
    private javax.swing.JTextField ctCargo;
    private javax.swing.JTextField ctCarteiraTrabalho;
    private javax.swing.JTextField ctCep;
    private javax.swing.JTextField ctCidade;
    private javax.swing.JTextField ctCpf;
    private javax.swing.JTextField ctDigito;
    private javax.swing.JTextField ctEmail;
    private javax.swing.JTextField ctEstado;
    private javax.swing.JTextField ctIdade;
    private javax.swing.JTextField ctNome;
    private javax.swing.JTextField ctNumero;
    private javax.swing.JTextField ctNumeroCartao;
    private javax.swing.JTextField ctOperacao;
    private javax.swing.JTextField ctRua;
    private javax.swing.JTextField ctSalario;
    private javax.swing.JTextField ctSobrenome;
    private javax.swing.JTextField ctTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgencia;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCarteiraTrabalho;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDadosPessoais;
    private javax.swing.JLabel lblDigito;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEndereco1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFilme;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroCartao;
    private javax.swing.JLabel lblOperacao;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTable tblAtendente;
    // End of variables declaration//GEN-END:variables
}
